Repository mala-project/mala, pull requests merged in 2024-06, with the labels that each got.

#538 Revert "Restrict usage of cache to PRs:"
  .github/workflows/cpu-tests.yml
Labels: bug, CI/CD

#539 Allow CI runs for normal PRs, but avoid runs for draft PRs
  .github/workflows/cpu-tests.yml
  .github/workflows/gh-pages.yml
Labels: CI/CD

#540 openPMD I/O: fix parallel flushing
  mala/common/physical_data.py
Labels: bug

#543 This fixes Node.js 16 deprecation warnings in cpu-tests.yml
  .github/workflows/cpu-tests.yml
Labels: CI/CD

#544 Remove caches after pushes to develop/master (+tags)
  .github/workflows/cleanup-caches.yml
Labels: CI/CD

#547 Enhance diff output of Conda environments
  .github/workflows/cpu-tests.yml
Labels: not critical, CI/CD

#548 Use legacy builder to build Docker image
  .github/workflows/cpu-tests.yml
Labels: CI/CD
